# -*- coding: utf-8 -*-
"""Copy of sp500_reversals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vUphj1cWZhpx_pDFk9rLjAJa6Px7l7E_
"""

pip install yfinance 

"""# New Section

# New Section
"""

import yfinance as yf
df = yf.download('^GSPC', auto_adjust=True)
df['reversal %'] = (df['Close'] / df['Low'] - 1) *100
df.sort_values('reversal %', ascending=False).head(10).iloc[:,-1].reset_index()

df['reversal rank'] = df['reversal %'].rank(ascending=False)
df.tail()

len(df)

df['next_day_ret'] = (df.Close.shift(-1) / df.Close -1)*100

print(df.sort_values('reversal rank').iloc[:100,-1].describe())
df.sort_values('reversal rank').iloc[:100,-1].hist(bins=100)

